server {
    listen 80;
    server_name 150.158.103.51;

    # Max upload size
    client_max_body_size 10M;

    location / {
        proxy_pass http://unix:/root/qftcourse/qftcourse.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static {
        alias /root/qftcourse/app/static;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location /uploads {
        alias /root/qftcourse/app/uploads;
        expires 30d;
    }
}
