# Generated by Django 5.1.7 on 2026-03-29 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=100, verbose_name='学期名称')),
                ('slug', models.SlugField(unique=True, verbose_name='URL 标识')),
                ('is_current', models.BooleanField(default=False, verbose_name='当前学期')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
            ],
            options={
                'verbose_name': '学期',
                'verbose_name_plural': '学期',
                'db_table': 'semesters',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='作业标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='作业要求')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('is_published', models.BooleanField(default=False, verbose_name='已发布')),
                ('author', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.semester', verbose_name='所属学期')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'db_table': 'assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('author', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='courses.semester', verbose_name='所属学期')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'db_table': 'announcements',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order_index', models.IntegerField(default=0, verbose_name='排序序号')),
                ('title', models.CharField(max_length=200, verbose_name='章节标题')),
                ('slug', models.SlugField(blank=True, default='', max_length=100, verbose_name='URL 标识')),
                ('content', models.TextField(blank=True, default='', verbose_name='Markdown 内容')),
                ('is_published', models.BooleanField(default=False, verbose_name='已发布')),
                ('author', models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'ta']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='编辑人')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.semester', verbose_name='所属学期')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
                'db_table': 'chapters',
                'ordering': ['order_index'],
                'unique_together': {('semester', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('file', models.FileField(upload_to='homework/%Y/%m/', verbose_name='作业文件')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(bytes)')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='评分')),
                ('feedback', models.TextField(blank=True, default='', verbose_name='评语')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.assignment', verbose_name='所属作业')),
                ('student', models.ForeignKey(limit_choices_to={'role__in': ['student', 'ta']}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='提交学生')),
            ],
            options={
                'verbose_name': '作业提交',
                'verbose_name_plural': '作业提交',
                'db_table': 'submissions',
                'ordering': ['-created_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
