# Generated by Django 5.1.7 on 2026-03-29 03:33

import courses.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, default='', help_text='教师上传的作业题目 PDF', upload_to=courses.models.assignment_attachment_path, verbose_name='作业附件（PDF）'),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_late',
            field=models.BooleanField(default=False, verbose_name='是否逾期'),
        ),
        migrations.AddField(
            model_name='submission',
            name='late_reason',
            field=models.TextField(blank=True, default='', verbose_name='逾期原因'),
        ),
        migrations.AddField(
            model_name='submission',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='留言/备注'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to=courses.models.submission_file_path, verbose_name='作业文件（PDF）'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='提交学生'),
        ),
    ]
