# Generated by Django 5.1.7 on 2026-03-29 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_assignment_attachment_submission_is_late_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='scored_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='评分时间'),
        ),
        migrations.AddField(
            model_name='submission',
            name='scored_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['teacher', 'ta']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL, verbose_name='评分人'),
        ),
    ]
