# Generated by Django 5.1.7 on 2026-03-29 08:03

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_scored_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='lecture_pdf',
            field=models.FileField(blank=True, default='', help_text='本章主讲义 PDF 文件（仅支持 PDF，不超过 20MB）', upload_to=courses.models.chapter_lecture_path, verbose_name='讲义 PDF'),
        ),
    ]
