# Generated by Django 5.1.7 on 2026-03-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_chapter_lecture_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='group',
            field=models.CharField(blank=True, choices=[('review', '基础回顾'), ('pathint', '路径积分'), ('gauge', '经典规范场'), ('quantize', '量子化'), ('symmetry', '对称性与破缺'), ('renorm', '重整化'), ('anomaly', '反常')], default='', help_text='用于首页知识图谱分组，不填则不显示在图谱中', max_length=20, verbose_name='知识图谱分组'),
        ),
    ]
