# Generated by Django 5.1.7 on 2026-05-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_add_chapter_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='group',
            field=models.CharField(blank=True, choices=[('review', '1 基础回顾'), ('pathint', '2 路径积分量子化'), ('gauge', '3 经典规范场'), ('quantize', '4 规范场量子化'), ('feynman', '5 费曼图计算基础'), ('loop', '6 圈图计算简介'), ('sym', '7 场论中的对称性'), ('symbrk', '8 对称性破缺总述'), ('ssb', '9 对称性的自发破缺'), ('renorm', '10 重整化'), ('rger', '11 重整化群'), ('anomaly', '12 反常'), ('grav', '13 规范-引力之联系')], default='', help_text='用于首页知识图谱分组，不填则不显示在图谱中', max_length=20, verbose_name='知识图谱分组'),
        ),
    ]
